### ISSUE TITLE
Consistent failures from remote_file resource in _ohai recipe.

### ISSUE THREAD

**Issue by ghost** [the-galley/rackspace_support#15]
I'm seeing this issue in kitchen in two customers:
## chef-client errors

...
...
       Recipe: rackspace_support::_ohai
         \* directory[/etc/chef/ohai_plugins] action create (up to date)
         \* remote_file[/etc/chef/ohai_plugins/rackconnect.rb] action create

```
       ================================================================================
       Error executing action `create` on resource 'remote_file[/etc/chef/ohai_plugins/rackconnect.rb]'
       ================================================================================

       EOFError
       --------
       end of file reached

       Cookbook Trace:
       ---------------
       /tmp/kitchen/cache/cookbooks/rackspace_support/recipes/_ohai.rb:36:in `from_file'
       /tmp/kitchen/cache/cookbooks/rackspace_support/recipes/default.rb:29:in `block in from_file'
       /tmp/kitchen/cache/cookbooks/rackspace_support/recipes/default.rb:28:in `each'
       /tmp/kitchen/cache/cookbooks/rackspace_support/recipes/default.rb:28:in `from_file'
       /tmp/kitchen/cache/cookbooks/2962274-shareholder/recipes/default.rb:17:in `block in from_file'
       /tmp/kitchen/cache/cookbooks/2962274-shareholder/recipes/default.rb:16:in `each'
       /tmp/kitchen/cache/cookbooks/2962274-shareholder/recipes/default.rb:16:in `from_file'

       Resource Declaration:
       ---------------------
       # In /tmp/kitchen/cache/cookbooks/rackspace_support/recipes/_ohai.rb

        30: remote_file ::File.join(node['ohai']['plugin_path'], 'rackconnect.rb') do
        31:   source 'https://raw.githubusercontent.com/rackerlabs/ohai-plugins/master/plugins/rackconnect.rb'
        32:   owner 'root'
        33:   group 'root'
        34:   mode 0755
        35:   action :nothing
        36: end.run_action :create
        37: 
        38: remote_file ::File.join(node['ohai']['plugin_path'], 'public_info.rb') do
        39:   source 'https://raw.githubusercontent.com/rackspace-cookbooks/platformstack/master/files/default/public_info.rb'
        40:   owner 'root'
        41:   group 'root'
        42:   mode 0755
        43:   action :nothing
        44: end.run_action :create
        45: 
        46: ohai('reload_ohai_for_rs').run_action :reload

       Compiled Resource:
       ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/rackspace_support/recipes/_ohai.rb:30:in `from_file'

       remote_file("/etc/chef/ohai_plugins/rackconnect.rb") do
         provider Chef::Provider::RemoteFile
         action [:nothing]
         retries 0
         retry_delay 2
         default_guard_interpreter :default
         path "/etc/chef/ohai_plugins/rackconnect.rb"
         backup 5
         atomic_update true
         source ["https://raw.githubusercontent.com/rackerlabs/ohai-plugins/master/plugins/rackconnect.rb"]
         use_etag true
         use_last_modified true
         declared_type :remote_file
         cookbook_name "rackspace_support"
         recipe_name "_ohai"
         owner "root"
         group "root"
         mode 493
       end
```

---

When I'm on our VPN, I get the EOFError. When I'm on my network at home I'm getting SocketError when attempting to connect to url 'https://raw.githubusercontent.com/rackerlabs/ohai-plugins/master/plugins/rackconnect.rb'.

I'm able to do a 'kitchen login' and wget and curl the file to the local filesystem on both networks.

Completely stumped on how to troubleshoot this moving forward.

**Comment by ghost** [comment]
May be local config issue. Further testing underway. Will close with solution if resolved locally. Please let me know if any others reproduce the issue.

**Comment by ghost** [comment]
Confirmed this is a local workstation issue. While I've found a resolution by changing workstations, I've yet to find the root cause. Closing issue for now.
