### ISSUE TITLE
RuntimeError: must have rackconnect ohai plugin installed

### ISSUE THREAD

**Issue by martinb3** [the-galley/rackspace_support#8]
There appears to be some sort of race condition or missing transitive dependency when running this on a new machine for the first time:

```
       * ohai[reload_ohai_for_rs] action reload
           - re-run ohai and merge results into node attributes

         ================================================================================
         Recipe Compile Error in /tmp/kitchen/cache/cookbooks/base_cookbook/recipes/default.rb
         ================================================================================

         RuntimeError
         ------------
         must have rackconnect ohai plugin installed

         Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/rackspace_support/recipes/default.rb:32:in `from_file'
           /tmp/kitchen/cache/cookbooks/base_cookbook/recipes/default.rb:28:in `block in from_file'
           /tmp/kitchen/cache/cookbooks/base_cookbook/recipes/default.rb:27:in `each'

       [2015-05-14T12:35:50+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
         Chef Client failed. 7 resources updated in 33.321802105 seconds
       [2015-05-14T12:35:50+00:00] ERROR: must have rackconnect ohai plugin installed
       [2015-05-14T12:35:50+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
-----> Destroying <default-ubuntu-1404>...
```

I'm wondering if this a race condition or perhaps a bug because of a dependency missing in ohai. Platformstack appears to install this correctly, so I'm going to refer to that to start troubleshooting it.

**Comment by martinb3** [comment]
The recipe that caused this looks like:

``````
include_recipe 'rackspace_support::default'
if rackconnected? ...```
``````

**Comment by jarosser06** [comment]
Should be resolved with https://github.com/jarosser06/chef-sugar-rackspace/pull/10

**Comment by martinb3** [comment]
Appears it should be fixed. Will re-open if it comes back up.
